- name: Installing java
  package:
    name: java
    state: present

- name: Adding another user
  user:
    name: "{{APPUSER}}"
    comment: Adding the user

- name: Tomcat Installation
  unarchive:
    src: "{{TOMCAT_URL}}"
    dest: "{{APPUSER_HOME}}"
    remote_src: yes
  become_user: "{{APPUSER}}"