- name: Installing java
  package:
    name: java
    state: present

- name: Adding another user
  user:
    name: "{{APPUSER}}"
    comment: "Adding the user"

- name: Tomcat Installation
  unarchive:
    src: "{{TOMCAT_URL}}"
    dest: "{{APPUSER_HOME}}"
    remote_src: yes
  become_user: "{{APPUSER}}"

- name: WAR download
  get_url:
    url: "{{WAR_URL}}"
    dest: "{{APPUSER_HOME}}/apache-tomcat-8.5.81/webapps/"
    mode: '0775'
  become_user: "{{APPUSER}}"

- name: JAR download
  get_url:
    url: "{{JAR_URL}}"
    dest: "{{APPUSER_HOME}}/apache-tomcat-8.5.81/lib/"
    mode: '0775'
  become_user: "{{APPUSER}}"

- name: Copy the context.xml
  template:
    src: context.xml
    dest: "{{APPUSER_HOME}}/apache-tomcat-8.5.81/conf/"
    mode: '0775'
  become_user: "{{APPUSER}}"

- name: Installing Mariadb-Server 
  package:
    name: mariadb-server
    state: present

- name: Downlod the schema 
  get_url:
     url: "{{SCHEMA_URL}}"
     dest: /tmp/student.sql
  become_user: "{{APPUSER}}" 

- name: Starting Mariadb-Servre 
  service: 
    name: mariadb 
    state: started 

- name: Injecting the schema 
  shell: mysql < /tmp/student.sql

- name: Copying the systemd file 
  copy:  
    src: student.service
    dest: /etc/systemd/system/multi-user.target.wants/
    mode: '0775'

- name: Reload the student daemon 
  systemd:
    name: student
    state: restarted
    daemon_reload: yes

- name: Waitning for 8 sec 
  pause: 
    seconds: 8

- name: Assertion Testing of Student Availability Check 
  uri:
    url: http://localhost:8080/student

