- name: Installing the web server
  package:
    name: httpd

- name: Copying the proxy.conf file
  copy:
    src: proxy.conf
    dest: /etc/httpd/conf.d/proxy.conf
  notify: Restart HTTPD

- name: Downloading the index file
  copy:
    src: index.html
    dest: /var/www/html/index.html
  notify: Restart HTTPD

- name: Copy download image
  copy:
    src: download.jpg
    dest: /var/www/html/download.jpg
  


- name: Starting the HTTPD server
  service:
    name: httpd
    state: started
    enabled: yes


  