- name: Installing the web server
  package:
    name: httpd

- name: Starting the HTTPD server
  service:
    name: httpd
    state: started
    enabled: yes

- name: Copying the proxy.conf file
  copy:
    src: proxy.conf
    dest: /etc/httpd/conf.d/proxy.conf
  